SITES = [
    # Central Government
    {"name": "Defence", "url": "https://defproc.gov.in"},
    {"name": "CPPP Govt", "url": "https://eprocure.gov.in"},
    {"name": "CPPP CPSE", "url": "https://etenders.gov.in"},

    # PSUs
    {"name": "BHEL", "url": "https://eprocurebhel.co.in"},
    {"name": "Coal India", "url": "https://coalindiatenders.nic.in/nicgep/app"},
    {"name": "CPCL", "url": "https://cpcletenders.nic.in/nicgep/app"},
    {"name": "NTPC", "url": "https://eprocurentpc.nic.in/nicgep/app"},
    {"name": "IOCL", "url": "https://iocletenders.nic.in/nicgep/app"},
    {"name": "BEL", "url": "https://eprocurebel.co.in"},
    {"name": "GRSE", "url": "https://eprocuregrse.co.in"},
    {"name": "GSL", "url": "https://eprocuregsl.nic.in/nicgep/app"},
    {"name": "HSL", "url": "https://eprocurehsl.nic.in/nicgep/app"},
    {"name": "MDL", "url": "https://eprocuremdl.nic.in/nicgep/app"},
    {"name": "Midhani", "url": "https://eprocuremidhani.nic.in/nicgep/app"},

    # PMGSY (NIC-based mostly)
    {"name": "PMGSY NRRDA", "url": "https://www.pmgsytenders.gov.in/nicgep/app"},
    {"name": "PMGSY Andaman", "url": "https://pmgsytendersani.nic.in/nicgep/app"},
    {"name": "PMGSY Andhra Pradesh", "url": "https://pmgsytendersap.gov.in/nicgep/app"},
    {"name": "PMGSY Arunachal Pradesh", "url": "https://pmgsytendersarn.gov.in/nicgep/app"},
    {"name": "PMGSY Assam", "url": "https://pmgsytendersasm.gov.in/nicgep/app"},
    {"name": "PMGSY Bihar", "url": "https://pmgsytendersbih.gov.in/nicgep/app"},
    {"name": "PMGSY Chhattisgarh", "url": "https://pmgsytenderscg.nic.in/nicgep/app"},
    {"name": "PMGSY Goa", "url": "https://pmgsytendersgoa.gov.in/nicgep/app"},
    {"name": "PMGSY Gujarat", "url": "https://pmgsytendersguj.gov.in/nicgep/app"},
    {"name": "PMGSY Haryana", "url": "https://pmgsytendershry.nic.in/nicgep/app"},
    {"name": "PMGSY Himachal Pradesh", "url": "https://pmgsytendershp.gov.in/nicgep/app"},
    {"name": "PMGSY J&K", "url": "https://pmgsytendersjk.gov.in/nicgep/app"},
    {"name": "PMGSY Jharkhand", "url": "https://pmgsytendersjhr.gov.in/nicgep/app"},
    {"name": "PMGSY Karnataka", "url": "https://pmgsytenderskar.gov.in/nicgep/app"},
    {"name": "PMGSY Kerala", "url": "https://pmgsytendersker.gov.in/nicgep/app"},
    {"name": "PMGSY Ladakh", "url": "https://pmgsytendersla.nic.in/nicgep/app"},
    {"name": "PMGSY Madhya Pradesh", "url": "https://pmgsytendersmp.gov.in/nicgep/app"},
    {"name": "PMGSY Maharashtra", "url": "https://pmgsytendersmah.gov.in/nicgep/app"},
    {"name": "PMGSY Manipur", "url": "https://pmgsytendersman.gov.in/nicgep/app"},
    {"name": "PMGSY Meghalaya", "url": "https://pmgsytendersmeg.gov.in/nicgep/app"},
    {"name": "PMGSY Mizoram", "url": "https://pmgsytendersmiz.gov.in/nicgep/app"},
    {"name": "PMGSY Nagaland", "url": "https://pmgsytendersngl.gov.in/nicgep/app"},
    {"name": "PMGSY Odisha", "url": "https://pmgsytendersori.gov.in/nicgep/app"},
    {"name": "PMGSY Puducherry", "url": "https://pmgsytenderspy.nic.in/nicgep/app"},
    {"name": "PMGSY Punjab", "url": "https://pmgsytenderspb.gov.in/nicgep/app"},
    {"name": "PMGSY Rajasthan", "url": "https://pmgsytendersraj.gov.in/nicgep/app"},
    {"name": "PMGSY Sikkim", "url": "https://pmgsytendersskm.gov.in/nicgep/app"},
    {"name": "PMGSY Tamil Nadu", "url": "https://pmgsytenderstn.gov.in/nicgep/app"},
    {"name": "PMGSY Telangana", "url": "https://pmgsytendersts.nic.in/nicgep/app"},
    {"name": "PMGSY Tripura", "url": "https://pmgsytenderstrp.gov.in/nicgep/app"},
    {"name": "PMGSY Uttarakhand", "url": "https://pmgsytendersuk.gov.in/nicgep/app"},
    {"name": "PMGSY Uttar Pradesh", "url": "https://pmgsytendersup.gov.in/nicgep/app"},
    {"name": "PMGSY West Bengal", "url": "https://pmgsytenderswb.gov.in/nicgep/app"},

    # State portals (NIC-based)
    {"name": "Andaman", "url": "https://eprocure.andaman.gov.in/nicgep/app"},
    {"name": "Arunachal Pradesh", "url": "https://arunachaltenders.gov.in/nicgep/app"},
    {"name": "Assam", "url": "https://assamtenders.gov.in/nicgep/app"},
    {"name": "Chandigarh", "url": "https://etenders.chd.nic.in/nicgep/app"},
    {"name": "Dadra Nagar Haveli", "url": "https://dnhtenders.gov.in/nicgep/app"},
    {"name": "Daman Diu", "url": "https://ddtenders.gov.in/nicgep/app"},
    {"name": "Delhi", "url": "https://govtprocurement.delhi.gov.in/nicgep/app"},
    {"name": "Goa", "url": "https://eprocure.goa.gov.in/nicgep/app"},
    {"name": "Haryana", "url": "https://etenders.hry.nic.in/nicgep/app"},
    {"name": "Himachal Pradesh", "url": "https://hptenders.gov.in/nicgep/app"},
    {"name": "Jammu Kashmir", "url": "https://jktenders.gov.in/nicgep/app"},
    {"name": "Jharkhand", "url": "https://jharkhandtenders.gov.in/nicgep/app"},
    {"name": "Kerala", "url": "https://etenders.kerala.gov.in/nicgep/app"},
    {"name": "Lakshadweep", "url": "https://tendersutl.gov.in/nicgep/app"},
    {"name": "Maharashtra", "url": "https://mahatenders.gov.in/nicgep/app"},
    {"name": "Madhya Pradesh", "url": "https://mptenders.gov.in/nicgep/app"},
    {"name": "Manipur", "url": "https://manipurtenders.gov.in/nicgep/app"},
    {"name": "Meghalaya", "url": "https://meghalayatenders.gov.in/nicgep/app"},
    {"name": "Mizoram", "url": "https://mizoramtenders.gov.in/nicgep/app"},
    {"name": "Nagaland", "url": "https://nagalandtenders.gov.in/nicgep/app"},
    {"name": "Odisha", "url": "https://tendersodisha.gov.in/nicgep/app"},
    {"name": "Puducherry", "url": "https://pudutenders.gov.in/nicgep/app"},
    {"name": "Punjab", "url": "https://eproc.punjab.gov.in/nicgep/app"},
    {"name": "Rajasthan", "url": "https://eproc.rajasthan.gov.in/nicgep/app"},
    {"name": "Sikkim", "url": "https://sikkimtender.gov.in/nicgep/app"},
    {"name": "Tamil Nadu", "url": "https://tntenders.gov.in/nicgep/app"},
    {"name": "Tripura", "url": "https://tripuratenders.gov.in/nicgep/app"},
    {"name": "Ladakh", "url": "https://tenders.ladakh.gov.in/nicgep/app"},
    {"name": "Uttarakhand", "url": "https://uktenders.gov.in/nicgep/app"},
    {"name": "Uttar Pradesh", "url": "https://etender.up.nic.in/nicgep/app"},
    {"name": "West Bengal", "url": "https://wbtenders.gov.in/nicgep/app"},
]